print("Nhap gia ve cap treo:")
a = int(input("   + Cua ng lon la: "))
b = int(input("   + Cua tre em la: "))
print("Nhap gia ve xe lua:")
u = int(input("   + Cua ng lon la: "))
v = int(input("   + Cua tre em la: "))
x = int(input("Nhap tong so ng di la: "))
y = int(input("Nhap tong so tre em la: "))
s =  a*(x-y) + u*(x-y) + b*y + v*y
print("Tong so tien ve la:", s)
